name: push-workflow 1  # 워크플로우의 이름을 정의합니다.

on: push  # push 이벤트가 발생할 때 워크플로우가 트리거됩니다.

jobs:  # 워크플로우에서 실행할 작업들을 정의합니다.
  push-job:  # 작업의 이름을 정의합니다.

    runs-on: ubuntu-latest  # 작업이 실행될 환경을 지정합니다. 최신 버전의 Ubuntu에서 실행됩니다.

    steps:  # 작업 내에서 실행할 개별 단계들을 정의합니다.
      - name: step1  # 첫 번째 단계의 이름을 정의합니다.
        run: echo Hello, world!  # "Hello, world!"를 출력하는 명령어를 실행합니다.

      - name: step2  # 두 번째 단계의 이름을 정의합니다.
        run: |  # 여러 줄의 명령어를 실행할 수 있도록 합니다.
          echo "Hello, world!"  # "Hello, world!"를 출력합니다.
          echo github actions  # "github actions"를 출력합니다.
          


