name: cache

on:
  push:
    paths:
      - "my-app/**"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout # 코드 체크아웃
        uses: actions/checkout@v4
      - name: setup-node # 노드 설정
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node.js modules # 노드 모듈 캐시
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies # 의존성 설치
        run: |
          cd my-app
          npm ci
      - name: npm build # 빌드
        run: |
          cd my-app
          npm run build
