name: artifact

on:
  push

jobs: # 작업 정의
  upload-artifact: # 아티팩트 업로드
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - name: echo # 콘솔 출력
        run: echo "Hello, world!" > hello.txt
      - name: upload-artifact # 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: artifact-test
          path: ./hello.txt

  download-artifact: # 아티팩트 다운로드
    runs-on: ubuntu-latest # 실행 환경
    needs: upload-artifact # 이전 작업 종속성
    steps:
      - name: download-artifact # 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: artifact-test
          path: ./
      - name: check # 파일 확인
        run: cat hello.txt

